### ISSUE TITLE
[Bug]: Today's Feeding Quantity is miscalculated

### ISSUE THREAD

**Issue by crbarahona** [jjjonesjr33/ha_petlibro#1]
### What happened ?

On multiple devices with different feeding schedules the today's feeding quantity is pretty far off. 

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/2f4cb38a-f513-42cf-b7fd-e86164dc7c76">

The feeding schedule is 2/12cup, 1/12cup, 1/12cup, 1/12cup. That shouldn't be near the 2.11cup it shows. 

### Relevant log output

```python
No relevant logs. Just enabled debug logging.
```

**Comment by jjjonesjr33** [comment]
Taking a look at it now.

**Comment by jjjonesjr33** [comment]
# Resolved
I found the issue. Initially, I think I was using grams by mistake. For some reason, the RFID was originally linked to the grain feeder. When I converted it into an independent device, it seems I accidentally left some of the code unchanged. 😆 

Original code:
```python
        # Handle today_feeding_quantity as raw numeric value, converting to cups
        elif sensor_key == "today_feeding_quantity":
            feeding_quantity = getattr(self.device, sensor_key, 0)
            cups = (feeding_quantity / 236.588) * 100
            return f"{round(cups, 2)}"
```
I've updated the code to base the feeding amount on the feeding_quantity from the API, this now should display the correct amount of food given. 

I'll be pushing an update shortly.

Corrected code:
```python
        # Handle today_feeding_quantity as raw numeric value, converting to cups
        elif sensor_key == "today_feeding_quantity":
            feeding_quantity = getattr(self.device, sensor_key, 0)
            # Convert feeding_quantity to cups, where 1/12 cup = 20 ml
            cups = feeding_quantity * (1 / 12)  # Since each 1 unit is 1/12 of a cup
            return f"{round(cups, 2)}"
```

**Comment by jjjonesjr33** [comment]
**Full Changelog**: https://github.com/jjjonesjr33/ha_petlibro/compare/RFID-v1.0.2...RFID-v1.0.3
